const actionKeys = [
  "new_account",
  "username",
  "bio",
  "profile_picture",
  "cover",
  "nip05",
  "luds",
  "relays_setup",
  "topics_setup",
  "follow_yaki",
  "flashnews_draft",
  "flashnews_post",
  "un_write",
  "un_rate",
  "curation_post",
  "article_post",
  "article_draft",
  "video_post",
  "bookmark",
  "zap",
  "reaction",
  "comment_post",
];

const chartActionKeys = [
  "flashnews_draft",
  "flashnews_post",
  "un_write",
  "un_rate",
  "curation_post",
  "article_post",
  "article_draft",
  "video_post",
  "bookmark",
  "zap",
  "reaction",
  "dms",
  "user_impact",
  "comment_post",
];
export { chartActionKeys, actionKeys };
