export default [
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/yakihonne.png",
    main_tag: "YakiHonne",
    sub_tags: [
      "YakiHonne Discover Bali",
      "YakiHonne Project Spotlight",
      "Make NOSTR Better",
      "Make nostr Better",
      "Make Nostr Better",
      "YakiHonne Imagination Intelligence Ideathon",
      "Yakihonne",
      "YakiHonne",
      "yakihonne",
    ],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/news.png",
    main_tag: "News",
    sub_tags: [
      "News",
      "Media",
      "Marty's Ƀent",
      "Cuba",
      "SEC",
      "USA",
      "Right Shift%20",
      "ThaiNostrich",
      "SOCIAL MEDIA",
      "Right Shift",
      "China",
      "Africa",
      "ukraine",
      "War",
    ],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/travel.png",
    main_tag: "Travel",
    sub_tags: [
      "TRAVEL",
      "YakiHonne Discover Bali",
      "Bali",
      "Camping",
      "Camping Car",
    ],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/technology.png",
    main_tag: "Technology",
    sub_tags: [
      "Technology",
      "YakiHonne Project Spotlight",
      "YakiHonne Discover Bali",
      "Digital Transformation",
      "software development",
      "Blockchain",
      "blockchain",
      "Decentralization",
      "Robotics",
      "OpenAI",
      "privacy",
      "Artificial Intelligence",
      "ARTIFICIAL INTELLIGENCE",
      "Tech",
      "TECH",
      "INNOVATION",
      "programming",
      "Cybersecurity",
      "Nvidia",
      "languages",
      "Robots",
      "ai",
      "twitter",
      "Twitter",
      "Apple",
      "Microsoft",
      "Google",
      "Security",
      "TECHNICAL",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/crypto.png",
    main_tag: "Crypto",
    sub_tags: [
      "blockchain",
      "Blockchain",
      "Crypto",
      "crypto",
      "Cryptocurrency",
      "cryptocurrency",
      "Cryptocurrencies",
      "Cryptography",
      "web3",
      "Web3",
      "ethereum",
      "Ethereum",
      "ETH",
      "ETF",
      "Decentralization",
      "mining",
      "lightning",
      "Binance",
      "Coinbase",
      "Price Analysis",
      "Altcoin",
      "XRP",
      "DeFi",
      "Exchange",
      "uniswap",
      "Grayscale",
    ],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/bitcoin.png",
    main_tag: "Bitcoin",
    sub_tags: [
      "blockchain",
      "Blockchain",
      "Bitcoin",
      "bitcoin",
      "BITCOIN",
      "BTC",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/social.png",
    main_tag: "Social",
    sub_tags: [
      "plebchain",
      "Social Media",
      "twitter",
      "Twitter",
      "Social Network",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/nostr.png",
    main_tag: "Nostr",
    sub_tags: [
      "Nostr",
      "NOSTR",
      "Make NOSTR Better",
      "plebchain",
      "pleb",
      "guide",
      "#plebchain",
      "#pleb",
      "zaps",
      "artonnostr",
      "Decentralization",
      "#nostr",
      "lightning",
      "NostrTechWeekly",
      "NostReport",
      "Lightning Network",
      "minibolt",
      "Open Source",
      "SATs",
      "zap",
      "Zap",
      "Make nostr Better",
      "Make Nostr Better",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/economy.png",
    main_tag: "Economy",
    sub_tags: [
      "Economy",
      "economy",
      "ETF",
      "Stock Market",
      "stock market",
      "Twitter",
      "Social Network",
      "Japan",
      "World Bank",
      "Money",
      "Money",
      "economics",
      "inflation",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/finance.png",
    main_tag: "Finance",
    sub_tags: [
      "Finance",
      "finance",
      "Investment",
      "Trading",
      "trading",
      "Price Analysis",
      "Money",
      "Stock Market",
      "stock market",
      "Exchange",
      "Financial Market",
      "Grayscale",
      "SEC",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/gaming.png",
    main_tag: "Gaming",
    sub_tags: ["gaming", "game", "ps5games", "pcgames"],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/entrepreneurship.png",
    main_tag: "Entrepreneurship",
    sub_tags: [
      "business consultants",
      "enterprise modernization",
      "Investment",
      "business",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/writing.png",
    main_tag: "Writing",
    sub_tags: [
      "Writing",
      "writing",
      "blogging",
      "poetry",
      "literature",
      "#literature",
      "poem",
      "#poem",
      "author",
      "poetstr",
      "sonnet",
      "#sonnet",
      "#author",
      "#poetry ",
      "poemstr",
      "#poemstr",
      "#poet",
      "#poetstr",
      "#artonnostr",
      "original",
      "#original",
      "poet",
      "gita",
      "mahabharata",
      "gita.shutri.com",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/food.png",
    main_tag: "Food",
    sub_tags: [
      "Food",
      "Cooking",
      "nostrcooking",
      "#keto",
      "#low carb",
      "nostrcooking-sauce",
      "Vegetarian",
      "nostrcooking-breakfast",
      "nostrcooking-alcohol",
      "nostrcooking-american",
      "nutrition",
      "Vegetarianism",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/self-improvement.png",
    main_tag: "Self improvement",
    sub_tags: [
      "Productivity",
      "#self-discovery",
      "self-improvement",
      "self-esteem",
      "self-confidence",
      "Self",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/politics.png",
    main_tag: "Politics",
    sub_tags: [
      "Politics",
      "POLITICS",
      "politics",
      "política",
      "freedom",
      "Inmigración",
      "self-esteem",
      "self-confidence",
      "Self",
    ],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/psychology.png",
    main_tag: "Psychology",
    sub_tags: ["Psychology", "#psychology", "psychology"],
  },

  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/mental.png",
    main_tag: "Mental Health",
    sub_tags: [
      "MentalHealth",
      "#mental health",
      "Mindfulness",
      "extended mind",
      "#mind",
      "mindmaps",
      "brain",
    ],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/health.png",
    main_tag: "Health",
    sub_tags: [
      "Health",
      "#health",
      "#nutrition",
      "health",
      "#inflammation",
      "#obesity",
      "#diet",
      "#insulin",
      "#stress",
      "#medicine",
      "#immune function",
      "#omega 3 fatty acids",
      "diabetes",
    ],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/life.png",
    main_tag: "Life",
    sub_tags: [
      "love",
      "Family",
      "family",
      "#love",
      "philosophy",
      "#life",
      "#exercise",
      "#relationships",
      "kids",
      "Culture",
      "Relax",
    ],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/books.png",
    main_tag: "Books",
    sub_tags: ["books", "#books", "bookstr"],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/marketing.png",
    main_tag: "Marketing",
    sub_tags: ["marketing", "Investment"],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/art.png",
    main_tag: "Art",
    sub_tags: [
      "Art",
      "art",
      "#art",
      "#Art",
      "artonnostr",
      "painting",
      "oilpainting",
    ],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/entertainment.png",
    main_tag: "Entertainment",
    sub_tags: ["TFTC Podcast", "Social Media", "Podcast"],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/music.png",
    main_tag: "Music",
    sub_tags: ["Music", "music", "MUSIC", "#music"],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/photography.png",
    main_tag: "Photography",
    sub_tags: ["photography", "Photography", "#Photography"],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/sport.png",
    main_tag: "Sport",
    sub_tags: ["Sport", "sport", "sports", "#nutrition", "#exercise"],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/industry.png",
    main_tag: "Industry",
    sub_tags: ["Energy", "industry"],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/space.png",
    main_tag: "Space",
    sub_tags: ["Space", "SPACE", "space", "SpaceX", "NASA"],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/history.png",
    main_tag: "History",
    sub_tags: ["history", "History", "history channel"],
  },
  {
    icon: "https://yakihonne.s3.ap-east-1.amazonaws.com/topics_icons/animals.png",
    main_tag: "Animals",
    sub_tags: ["Dog", "Animal", "history channel"],
  },
];
